### ISSUE TITLE
getLocationMediasById API change

### ISSUE THREAD

**Issue by tomziwar** [postaddictme/instagram-java-scraper#110]
Method getLocationMediasById doesn't work anymore since yesterday.

It throws:
```
Exception Description: A descriptor with default root element graphql was not found in the project]
	at me.postaddict.instagram.scraper.mapper.ModelMapper.mapObject(ModelMapper.java:177)
	at me.postaddict.instagram.scraper.mapper.ModelMapper.mapLocation(ModelMapper.java:68)
	at me.postaddict.instagram.scraper.request.GetLocationRequest.mapResponse(GetLocationRequest.java:41)
	at me.postaddict.instagram.scraper.request.GetLocationRequest.mapResponse(GetLocationRequest.java:13)
	at me.postaddict.instagram.scraper.request.PaginatedRequest.requestInstagramResult(PaginatedRequest.java:39)
	at me.postaddict.instagram.scraper.Instagram.getLocationMediasById(Instagram.java:136)
```

It looks like the API has changed, because the location tag is now wrapped into graphql tag:
```
{  
   "graphql":{  
      "location":{ ... }
   },
   "logging_page_id":"..."
}
```

**Comment by tomziwar** [comment]
Thanks for quick fix. When are you planning to prepare a new release jar?

**Comment by igor-suhorukov** [comment]
@tomziwar [release 2.2](repo1.maven.org/maven2/com/github/igor-suhorukov/instagramscraper/2.2/) are waiting for repository sync
