### ISSUE TITLE
Location field in Media is never filled in.

### ISSUE THREAD

**Issue by evdh** [postaddictme/instagram-java-scraper#139]
When getting the media from an account, I get back the posts including the caption. However, although the post contains a location, this is never returned in the 'location' field of the media. Is this supposed to work? Or is there another way to find the location?

**Comment by viralvaghela** [comment]
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/type/TypeReference
	at me.postaddict.instagram.scraper.Instagram.<init>(Instagram.java:25)
	at application.Main.main(Main.java:27)
