### ISSUE TITLE
getMediaByUrl Issue

### ISSUE THREAD

**Issue by otopba** [postaddictme/instagram-java-scraper#67]
Hello!
```
Instagram instagram = new Instagram(new OkHttpClient()); 
Media media = instagram.getMediaByUrl("https://www.instagram.com/p/BWizrpZgg-w/");
```

This code produce exception. Seems that video mapping are wrong

```
Exception in thread "main" java.lang.IllegalArgumentException: javax.xml.bind.UnmarshalException
 - with linked exception:
[Exception [EclipseLink-25004] (Eclipse Persistence Services - 2.7.0.v20170811-d680af5): org.eclipse.persistence.exceptions.XMLMarshalException
Exception Description: An error occurred unmarshalling the document
Internal Exception: javax.json.stream.JsonParsingException: Unexpected char 60 at (line no=1, column no=1, offset=0)]
	at me.postaddict.instagram.scraper.mapper.ModelMapper.mapObject(ModelMapper.java:134)
	at me.postaddict.instagram.scraper.mapper.ModelMapper.mapMedia(ModelMapper.java:49)
	at me.postaddict.instagram.scraper.Instagram.getMediaByUrl(Instagram.java:101)
	at me.postaddict.instagram.scraper.Main.main(Main.java:11)
Caused by: javax.xml.bind.UnmarshalException
 - with linked exception:
[Exception [EclipseLink-25004] (Eclipse Persistence Services - 2.7.0.v20170811-d680af5): org.eclipse.persistence.exceptions.XMLMarshalException
Exception Description: An error occurred unmarshalling the document
Internal Exception: javax.json.stream.JsonParsingException: Unexpected char 60 at (line no=1, column no=1, offset=0)]
	at org.eclipse.persistence.jaxb.JAXBUnmarshaller.handleXMLMarshalException(JAXBUnmarshaller.java:1110)
	at org.eclipse.persistence.jaxb.JAXBUnmarshaller.unmarshal(JAXBUnmarshaller.java:172)
	at me.postaddict.instagram.scraper.mapper.ModelMapper.mapObject(ModelMapper.java:132)
	... 3 more
Caused by: Exception [EclipseLink-25004] (Eclipse Persistence Services - 2.7.0.v20170811-d680af5): org.eclipse.persistence.exceptions.XMLMarshalException
Exception Description: An error occurred unmarshalling the document
Internal Exception: javax.json.stream.JsonParsingException: Unexpected char 60 at (line no=1, column no=1, offset=0)
	at org.eclipse.persistence.exceptions.XMLMarshalException.unmarshalException(XMLMarshalException.java:120)
	at org.eclipse.persistence.internal.oxm.record.json.JsonStructureReader.parse(JsonStructureReader.java:146)
	at org.eclipse.persistence.internal.oxm.record.SAXUnmarshaller.unmarshal(SAXUnmarshaller.java:938)
	at org.eclipse.persistence.internal.oxm.record.SAXUnmarshaller.unmarshal(SAXUnmarshaller.java:414)
	at org.eclipse.persistence.internal.oxm.record.SAXUnmarshaller.unmarshal(SAXUnmarshaller.java:390)
	at org.eclipse.persistence.internal.oxm.XMLUnmarshaller.unmarshal(XMLUnmarshaller.java:394)
	at org.eclipse.persistence.jaxb.JAXBUnmarshaller.unmarshal(JAXBUnmarshaller.java:156)
	... 4 more
Caused by: javax.json.stream.JsonParsingException: Unexpected char 60 at (line no=1, column no=1, offset=0)
	at org.glassfish.json.JsonTokenizer.unexpectedChar(JsonTokenizer.java:532)
	at org.glassfish.json.JsonTokenizer.nextToken(JsonTokenizer.java:415)
	at org.glassfish.json.JsonParserImpl$NoneContext.getNextEvent(JsonParserImpl.java:222)
	at org.glassfish.json.JsonParserImpl$StateIterator.next(JsonParserImpl.java:172)
	at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:149)
	at org.glassfish.json.JsonReaderImpl.read(JsonReaderImpl.java:84)
	at org.eclipse.persistence.internal.oxm.record.json.JsonStructureReader.parse(JsonStructureReader.java:138)
	... 9 more
```

**Comment by igor-suhorukov** [comment]
Hi @otopba 
It is not a bug. You provide in method invalid URL.
I create test for such issue. Method throw IllegalArgumentException in case of malformed URL.
